version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mosquitto
    restart: unless-stopped

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./web_admin:/usr/share/nginx/html
    depends_on:
      - server
    restart: unless-stopped
